export const coinData = [
    {
      logo:'/assets/bitcoin.png',
      code:'BTC', 
      percent:0.52, 
      value:'$319.34'
    },
    {
      logo:'/assets/sol.png',
      code:'SOL', 
      percent:-2.89, 
      value:'$109.33'
    },
    {
      logo:'/assets/xrp.png',
      code:'XRP', 
      percent:-2.89, 
      value:'$109.33'
    },
    {
      logo:'/assets/ada.png',
      code:'ADA', 
      percent:-1.57, 
      value:'$0.614869'
    },
    {
      logo:'/assets/avax.png',
      code:'AVAX', 
      percent:-1.57, 
      value:'$0.614869'
    },
    {
      logo:'/assets/ada.png',
      code:'ADA', 
      percent:-1.57, 
      value:'$0.614869'
    },
    {
      logo:'/assets/avax.png',
      code:'AVAX', 
      percent:-1.57, 
      value:'$0.614869'
    },
  ]