export const trendingCoinData = [
    {
      logo:'/assets/bitcoin.png',
      code:'BTC', 
      percent:0.52, 
      value:'$319.34'
    },
    {
      logo:'/assets/eth.png',
      code:'SOL', 
      percent:0.21, 
      value:'$2,375.15'
    },
    {
      logo:'/assets/steth.png',
      code:'stETH', 
      percent:-0.34, 
      value:'$2,371.72'
    },
    {
      logo:'/assets/uni.png',
      code:'UNI', 
      percent:-4.02, 
      value:'$7.3192'
    },
    {
      logo:'/assets/cfg.png',
      code:'CFG', 
      percent:-1.76, 
      value:'$0.773600'
    },
  ]